[package]
name = "extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotext = "0.1.1"
html2text = "0.6.0"
pdf-extract = "0.7.2"
